

all: $(CONTIKI_PROJECT)  

 
PROJECT_SOURCEFILES  += Image.c
PROJECT_SOURCEFILES  += ImageDB.c
PROJECT_SOURCEFILES  += TransferUDP.c

#CONTIKI = ../..
CONTIKI =  /home/user/contiki-ng

include $(CONTIKI)/Makefile.include




