

all: $(CONTIKI_PROJECT)  

 
PROJECT_SOURCEFILES  += Image.c
PROJECT_SOURCEFILES  += ImageDB.c
PROJECT_SOURCEFILES  += TransferUDP.c





 #PROJECT_SOURCEFILES  += TransferCommons.c
 #PROJECT_SOURCEFILES  +=  UdpStream.c
 #PROJECT_SOURCEFILES  +=  CD1.c
 #PROJECT_SOURCEFILES  +=  TransferClient.c
 #PROJECT_SOURCEFILES  +=  /home/user/WIMA/samples/Contiki/include/*.*

#CONTIKI = ../..
CONTIKI =  /home/user/contiki-ng

include $(CONTIKI)/Makefile.include




